### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by Callisto95** [matben1611/T1-autonomous-driving#1]
- [ ] Blinker
- [ ] Scheibenwischer
- [ ] WLAN Kontrolle des T1

**Comment by matben1611** [comment]
- [ ] Body Enhancement (new Blender models)
- [ ] Park Assistant 
- [ ] Driving - Steering

**Comment by Callisto95** [comment]
https://www.instructables.com/How-to-Add-WiFi-Control-to-Any-Project-ESP32-Begin/
